[package]
name = "embedded-car"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", branch = "master", features = [
	"defmt",
	"integrated-timers",
	"nightly",
] }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", branch = "master", features = [
	"defmt",
	"time-driver-tim2",
	"nightly",
	"stm32f103c8",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", branch = "master", features = [
	"defmt",
	"nightly",
] }

defmt = "0.3"
defmt-rtt = "0.3"

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }

[profile.release]
codegen-units = 1
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true
