[package]
name = "car-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
btleplug = "0.10.3"
car-core = { version = "0.1.0", path = "../car-core" }
egui = "0.19.0"
futures = "0.3.25"
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4"] }
