[package]
name = "car-controller"
version = "0.1.0"
description = "A core to control the car via Bluetooth"
repository = "https://github.com/MrNossion/embedded-car"
authors = ["Milo Moisson"]
keywords = ["embedded", "car", "stm32f103c8", "bluetooth", "blue-pill"]
categories = ["embedded"]
readme = "README.md"
edition = "2021"
license = "MIT"

[dependencies]
car-core = { version = "0.1.0", path = "../car-core" }
car-transport = { version = "0.1.0", path = "../car-transport" }

btleplug = "0.10.4"
color-eyre = "0.6.2"
egui = "0.20.1"
futures = "0.3.25"
gilrs = "0.10.1"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4"] }
