[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Replace with the used chip as listed in `probe-run --list-chips`
runner = "probe-run --chip STM32F103C8"

[build]
target = "thumbv7m-none-eabi"

[alias]
rrun = "run --release"

[env]
DEFMT_LOG = "trace"
